version: '3'

services:

  VE-postgres:
    container_name: VE-postgres
    image: postgres:latest
    volumes:
      - ./Vol-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: editor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  VE-minio:
    container_name: VE-minio
    image: minio/minio:latest
    volumes:
      - ./Vol-Minio:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - 9001:9000
      - 9002:9001
    command: server /data --console-address ":9001"

  VE-RabbitMQ:
    image: rabbitmq:management
    container_name: VE-RabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - VE-minio
      - VE-postgres
      - VE-RabbitMQ
    ports:
      - 8000:8000



#  celery-worker:
#    container_name: celery-worker
#    build:
#      context: .
#      dockerfile: celery_worker.Dockerfile
#    depends_on:
#       - VE-RabbitMQ
#       - VE-postgres

