export const TRANSITION_TYPES = Object.freeze({
    SLIDE_RIGHT: 'SLIDE_RIGHT',
    SLIDE_LEFT: 'SLIDE_LEFT',
    SLIDE_TOP: 'SLIDE_TOP',
    SLIDE_BOTTOM: 'SLIDE_BOTTOM',
    ROTATE_RIGHT: 'ROTATE_RIGHT',
    ROTATE_LEFT: 'ROTATE_LEFT',
    FADE_IN: 'FADE_IN',
    FADE_OUT: 'FADE_OUT',
    ZOOM_IN: 'ZOOM_IN',
    ZOOM_OUT: 'ZOOM_OUT',
    SHAKE: 'SHAKE',
})